### PR TITLE
Updates to enrollment and attestation docs

### PR DESCRIPTION
**Pull request by nicowilliams**
Once [Safeboot.dev PR #125](https://github.com/osresearch/safeboot/pull/125) is merged, this should be merged as well.

Updates include:

 - attestation docs
 - enrollment docs and references to Safeboot.dev enrollment docs
 - updates to `send-to-tpm` and `tpm-receive` scripts to match the versions in Safeboot.dev

### CODE REVIEW

**Comment by tomoveu** [comment]
@nicowilliams okay, we will wait 125 on Safeboot. 

ps: I do not understand how Safeboot's PR affects the tutorial.

**Comment by nicowilliams** [comment]
I'm describing things about Safeboot in this PR that won't be true until that PR gets merged :)

**Comment by tomoveu** [comment]
Got it. Thanks :) 

Ping me when it's done.

**Comment by nicowilliams** [comment]
@tomoveu this is now ready.

**Comment by tomoveu** [comment]
Thank you @nicowilliams

**Pull request merged**
